# Generated by Django 3.2.8 on 2021-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_auto_20211216_1444'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WOVEN NARROW FAB', 'WOVEN NARROW FAB'), ('KNITTED NARROW FAB', 'KNITTED NARROW FAB')], default='WOVEN NARROW FAB', max_length=50)),
                ('code', models.CharField(choices=[('Elastic', 'Elastic'), ('Velcro', 'Velcro')], default=None, max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Elastic',
        ),
        migrations.DeleteModel(
            name='Velcro',
        ),
    ]
