# Generated by Django 3.2.8 on 2021-12-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtr', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('Elastic', 'Elastic'), ('Velcro', 'Velcro')], default='Elastic', max_length=50)),
                ('elastic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.elastic')),
                ('velcro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.velcro')),
            ],
        ),
    ]
