# Generated by Django 3.2.8 on 2021-12-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Bill', '0002_auto_20211216_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='elastic',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.elastic'),
        ),
        migrations.AlterField(
            model_name='temp',
            name='velcro',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.velcro'),
        ),
    ]
