# Generated by Django 3.2.8 on 2021-12-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_auto_20211216_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='code',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='elastic',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='velcro',
        ),
    ]
