# Generated by Django 3.2.8 on 2021-12-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211216_1444'),
        ('Bill', '0005_auto_20211216_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.item'),
        ),
    ]
