# Generated by Django 3.2.8 on 2021-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_temp_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='box',
            field=models.CharField(default='01', max_length=100),
        ),
    ]
