# Generated by Django 3.2.8 on 2021-12-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211216_1444'),
        ('Beneficiary', '0001_initial'),
        ('Bill', '0007_temp_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtr', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=100)),
                ('rate_without_gst', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('tamount', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('box', models.CharField(max_length=100)),
                ('bill_number', models.CharField(max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.item')),
            ],
        ),
        migrations.CreateModel(
            name='bill_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('freight_charges', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('NEFT', 'NEFT'), ('CASH', 'CASH')], max_length=50)),
                ('total_box', models.CharField(max_length=100)),
                ('tamount_without_gst', models.CharField(max_length=100)),
                ('ewaybill_number', models.CharField(default='-----------', max_length=100)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Beneficiary.recipient')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Beneficiary.transport')),
            ],
        ),
    ]
