# Generated by Django 3.2.8 on 2021-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0008_bill_details_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='formatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('invno', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
