# Generated by Django 3.2.8 on 2021-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0009_formatt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_details',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='discount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='freight_charges',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
