# Generated by Django 3.2.8 on 2021-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('gst', models.CharField(choices=[('I-GST', 'I-GST'), ('C-GST & S-GST', 'C-GST & S-GST')], default='I-GST', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=50)),
                ('add', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
